broker:
  host: "127.0.0.1"
  port: 9092
  checksum_enable: true
  offset_topic: "__consumer_offset"
  controllers:
    - controller_id: "controller-1"
      host: "127.0.0.1"
      port: 9093
    - controller_id: "controller-2"
      host: "127.0.0.1"
      port: 9094
    - controller_id: "controller-3"
      host: "127.0.0.1"
      port: 9095

  writer_config:
    max_batch_size:  64
    max_batch_bytes: 1048576     # 1024*1024 bytes
    max_batch_wait: 0.002
    max_workers: 4

controller:
  host: "127.0.0.1"
  port: 9093
  zk_hosts: "127.0.0.1:2181"
  controller_id: "controller-1"

log:
  log_dir: "./data/logs"
  retension_ms: 604800000        # 7 days
  rollover_ms: 3600000           # 1 hour
  max_segment_size: 134217728    # 128MB
  init_segment_size: 16777216    # 16MB
  segment_size_inc: 16777216     # 16MB growth
  segment_cache_size: 100

  cleaner_service_interval: 2.0
  flush_service_interval: 2.0

replica:
  id: "replica1"
  fetch_size: 1048576
  pool_wait: 1
  min_isr_count: 1
  max_isr_lag_ms: 10000