[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pylogstream-broker"
version = "0.1.0"
description = "PyLogStream broker node"
readme = "README.md"
requires-python = ">=3.11"

authors = [
    { name = "Akram Khan" }
]

dependencies = [
    "pylogstream-protocol>=0.1.0",
    "uvloop; sys_platform != 'win32'",
    "asyncio",
    "pyyaml"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-asyncio",
    "ruff",
    "mypy",
]

[project.scripts]
pylogstream-broker = "pylogstream_broker.network.broker:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
